/*
 * Legalesign API
 *
 * Legalesign.com is an electronic signature software. This is the documentation for its REST API.   Start by creating a trial account at https://app1.legalesign.com/auth/intro/. Upon account activation, select the API dev option.  Get an API key by emailing support@legalesign with background on your use-case and skills. You will need to show experience in API dev.  You will be in sandbox mode that will limit you to 5 signers. Add them on https://app1.legalesign.com/acc/settings/#api. Contact support to move to production mode when you are ready.  For any queries contact us at support@legalesign.com. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@legalesign.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MemberApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MemberApiTests
    {
        private MemberApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MemberApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MemberApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' MemberApi
            //Assert.IsInstanceOf(typeof(MemberApi), instance);
        }

        
        /// <summary>
        /// Test DeleteInvite
        /// </summary>
        [Test]
        public void DeleteInviteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid invitedId = null;
            //instance.DeleteInvite(invitedId);
            
        }
        
        /// <summary>
        /// Test DeleteMember
        /// </summary>
        [Test]
        public void DeleteMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid memberId = null;
            //instance.DeleteMember(memberId);
            
        }
        
        /// <summary>
        /// Test GetInvites
        /// </summary>
        [Test]
        public void GetInvitesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string group = null;
            //var response = instance.GetInvites(group);
            //Assert.IsInstanceOf(typeof(InvitedListResponse), response, "response is InvitedListResponse");
        }
        
        /// <summary>
        /// Test GetMember
        /// </summary>
        [Test]
        public void GetMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid memberId = null;
            //var response = instance.GetMember(memberId);
            //Assert.IsInstanceOf(typeof(MemberResponse), response, "response is MemberResponse");
        }
        
        /// <summary>
        /// Test GetMembers
        /// </summary>
        [Test]
        public void GetMembersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string group = null;
            //int? offset = null;
            //int? limit = null;
            //var response = instance.GetMembers(group, offset, limit);
            //Assert.IsInstanceOf(typeof(MemberListResponse), response, "response is MemberListResponse");
        }
        
        /// <summary>
        /// Test PostMember
        /// </summary>
        [Test]
        public void PostMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MemberPost memberPost = null;
            //instance.PostMember(memberPost);
            
        }
        
    }

}
